version: '2'
services:
  applicationinsightsdemo-app:
    image: applicationinsightsdemo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://applicationinsightsdemo-mysql:3306/applicationinsightsdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  applicationinsightsdemo-mysql:
    extends:
      file: mysql.yml
      service: applicationinsightsdemo-mysql
